name: Build the website
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-the-website:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16']
    env:
      TERM: xterm
      TZ: America/Los_Angeles
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install and Build
        run: |
          npm install
          npm run build
          touch build/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: build
